version: '2'

services:
  insync-app:
    image: tiredofit/insync
    container_name: insync-app
    environment:
      - CONTAINER_NAME=insync-app

      - INSYNC1_USERNAME=user@gmail.com
      - INSYNC1_AUTH_CODE=12345
      - INSYNC_DOWNLOAD=open-document
 
    volumes:
      - ./data:/data
    restart: always
